/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obpacmanobjetos;

import java.applet.AudioClip;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Brenda
 */
public class Felicidades extends javax.swing.JFrame {
   ImageIcon ima1 =new ImageIcon(getClass().getResource("/imagenes/ruu.gif"));//FONDO
   ImageIcon ima2=new ImageIcon(getClass().getResource("/imagenes/gan.gif"));//
   ImageIcon ima3=new ImageIcon(getClass().getResource("/imagenes/confeti.gif"));//FONDO
    
   public Felicidades() {
        initComponents();
        ImageIcon icono = new ImageIcon(ima1.getImage().getScaledInstance(fondo.getWidth(),fondo.getHeight(),Image.SCALE_DEFAULT));
        fondo.setIcon(icono);//fondo
        ImageIcon icono2= new ImageIcon(ima2.getImage().getScaledInstance(baile.getWidth(),baile.getHeight(),Image.SCALE_DEFAULT));
        baile.setIcon(icono2);//baile
        ImageIcon icono3= new ImageIcon(ima3.getImage().getScaledInstance(confeti.getWidth(),confeti.getHeight(),Image.SCALE_DEFAULT));
        confeti.setIcon(icono3);//fondo confeti
        AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/musica/musicaEspera.wav"));
        sonido.loop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        confeti = new javax.swing.JLabel();
        baile = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 378, 100, 30));
        getContentPane().add(confeti, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 380, 440));
        getContentPane().add(baile, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 260, 330));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        AudioClip sonido;
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/musica/clic.wav"));
        sonido.play();
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Felicidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Felicidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Felicidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Felicidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Felicidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baile;
    private javax.swing.JLabel confeti;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
